name: Deploy web frontend to local stage

on:
  push:
    branches: 
      - develop
      - Issue-**
    paths:
      - .github/workflows/local-www-deploy.yml
      - vue.js/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: |
        echo $GITHUB_WORKFLOW

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key:  ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install Packages
      run: |
        pwd
        ls -al
        yarn install
      working-directory: ./vue.js

    - name: Build
      run: |
        yarn build
      working-directory: ./vue.js

    - name: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.BYFS_LOCAL_S3_WEBHOSTING_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.BYFS_LOCAL_S3_WEBHOSTING_SECRET_KEY }}
      run: |
        aws s3 sync \
          --acl public-read \
          ./vue.js/dist s3://byfs-local.ghilbut.com
