name: Deploy web frontend to local stage

on:
  push:
    branches: 
      - Issue-3

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: Issue-3
        path: ./vue.js

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      with:
        path: "${{ steps.yarn-cache.outputs.dir }}"
        key: "${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}"
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install Packages
      working-directory: './vue.js'
      run: |
        pwd
        ls -al
        yarn install

    - name: Build
      working-directory: './vue.js'
      run: |
        pwd
        ls -al
        yarn build

    - name: deploy
      env:
        AWS_ACCESS_KEY_ID: "${{ secrets.BYFS_LOCAL_S3_WEBHOSTING_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.BYFS_LOCAL_S3_WEBHOSTING_SECRET_KEY }}"
      working-directory: './vue.js'
      run: |
        aws s3 sync \
          --acl public-read \
          ./dist s3://byfs-local.ghilbut.com
